"""
types.py

Small shared types for the LLM package.
"""

from dataclasses import dataclass
from typing import Optional

from src.llm.schemas import AgentTurn


@dataclass
class LLMResponse:
    """Result of an LLM call for an agent turn.

    Includes token usage:
    - prompt_tokens: input tokens sent to the model
    - completion_tokens: output tokens generated by the model
    - total_tokens: sum of the above
    """
    turn: AgentTurn
    prompt_tokens: Optional[int] = None
    completion_tokens: Optional[int] = None
    total_tokens: Optional[int] = None
    model: Optional[str] = None
    raw_response: Optional[str] = None  # for debugging if needed
